# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('create_on', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.FloatField()),
                ('support_email', models.CharField(blank=True, max_length=255, null=True)),
                ('support_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_operator',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('create_on', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.FloatField()),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_subscriber',
            },
        ),
    ]
